### ISSUE TITLE
Bool property with default value works not properly

### ISSUE THREAD

**Issue by fr05t1k** [jinzhu/configor#34]
I have a problem with a default value for a boolean property.
```go
type Config struct {
	Silent bool `default:"true"`
}
```
Yaml:

```yaml
silent: false
```
Result:
```go
err := configor.Load(conf, *configPath)
if err != nil {
	log.Fatal(err)
}
log.Println(conf.Silent)
```

**Actual**:
```
true
```
**Expected**:
```
false
```

**Comment by jerson** [comment]
related to this line: 

https://github.com/jinzhu/configor/blob/master/utils.go#L206

**Comment by LepX** [comment]
Is anyone fix this problem ? I got same question.

**Comment by alexandruionica** [comment]
I have the same issue.

**Comment by erikgrinaker** [comment]
This is a general problem with all data types, not just booleans. If a default value is set, and the user tries to override it with a zero value ("", 0, false), then the override will not take effect.

This is because the order in which values are applied is incorrect. Values are first loaded from files, then from environment variables, and only then are defaults applied - this is too late, because it is not possible to differentiate between a value that has not been set and one which has been explicitly set empty. Default values must be applied first.

Unfortunately I don't have time to make a PR right now. Maybe in a while.

**Comment by minitauros** [comment]
One workaround for this would be to make the type a pointer to a bool (`*bool`) instead of a bool. That way when the `DeepEqual` is called it will see that the interface does not equal the zero interface (because a pointer to a bool != nil), and therefore in this example the value would be a pointer to false instead of false. It's not the nicest to work with, but it will work.

**Comment by peterfraedrich** [comment]
Any update on a fix for this? This is a huge issue and its causing all kinds of problems for a project I'm working on.

**Comment by alexandruionica** [comment]
Same as @peterfraedrich , this is quite a big issue for me too.

**Comment by NeoyeElf** [comment]
@jinzhu it's a big issue for me too, any progress?

**Comment by al-2401** [comment]
@jinzhu it's a big issue for me too, any progress?

**Comment by beaquant** [comment]
issue open over 1 year, any progress? it appear again @jinzhu 
And if element is bool in structure, `required true`, it's can't find it with error `xxx is required, but blank`

**Comment by edhaight** [comment]
Any update on a fix? @jinzhu

**Comment by peterfraedrich** [comment]
Doesnt appear that @jinzhu is going to fix this as the last commit to master was 9 months ago. I've gone ahead and moved all my projects to use [github.com/spf13/viper](github.com/spf13/viper) for all the config needs.

**Comment by beaquant** [comment]
thanks, it work now
